# Generated by Django 4.1.6 on 2023-04-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpnl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendsms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('message', models.IntegerField(default=0)),
            ],
        ),
    ]
