# Generated by Django 4.1.6 on 2023-04-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpnl', '0002_sendsms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='sendsms',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
