# Generated by Django 4.1.6 on 2023-04-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpnl', '0003_delete_document_alter_sendsms_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
